#!/usr/bin/python3

import  sys, time, datetime, sync

def dateTag(dateString):
    WEEK_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    date = int(time.mktime(time.strptime(dateString, "%Y-%m-%d")))
    todayDate = datetime.datetime.today().strftime("%Y-%m-%d")
    today =  int(time.mktime(time.strptime(todayDate, "%Y-%m-%d")))
    diff = int((date-today)/86400) # difference in days
    if (diff < 0): # Overdue
        color = "\033[31m" # Red
    elif (diff == 0): # Due today
        return "\033[31mTODAY\033[00m" # Red
    elif (diff == 1): # Due tomorrow
        return "\033[33mTOMORROW\033[00m" # Yellow
    elif (diff <= 7): # Due this week
        return "\033[32m{}\033[00m".format(
                    WEEK_DAYS[(datetime.date.today().weekday()+diff)%7]) # Green
    else:
        color = "\033[00m" # Normal
    return "{}{}\033[00m".format(color, dateString)

def run():
    data = sync.getData()
    projects = data["projects"]
    tasks = data["tasks"]
    ids = data["ids"]
    # If not input is added, assume show.
    if (len(sys.argv) == 0):
        sys.argv.append("show")

    if sys.argv[0] == "add":
        if ("-p" in sys.argv):
            project = ids[int(sys.argv[sys.argv.index("-p")+1])]["id"]
        else:
            project = projects[0]["id"]
        if ("-d" in sys.argv):
            date = sys.argv[sys.argv.index("-d")+1]
        else:
            date = (datetime.date.today() + datetime.timedelta(days=1)).strftime("%Y-%m-%d")
        sync.addTask(sys.argv[1], project, date)

    elif sys.argv[0] == "done":
        del sys.argv[0]
        for id in sys.argv:
            sync.closeTask(ids[int(id)]["id"])

    elif sys.argv[0] == "show":
        i=0
        for project in projects:
            print(u"({:<3}) \033[4;1m{}\033[00m".format(i, project["name"]))
            i += 1
            for task in tasks:
                if (task["project_id"] == project["id"]):
                    print(u"({:<3})\t{} - {}".format(i, dateTag(task["due"]["date"]), 
                                                        task["content"]))
                    i += 1
    elif sys.argv[0] == "sync":
        sync.sync()
    else:
        print("Input not recognized")

if __name__ == "__main__":
    del sys.argv[0] # First argument is always the program name.
    run()